name: fretbursts_notebooks_env

channels:
- conda-forge

dependencies:
- cycler=0.10.0
- fontconfig=2.11.1
- freetype=2.5.5
- fretbursts
- funcsigs=0.4
- future=0.15.2
- hdf5=1.8.15.1
- libgfortran=3.0
- libpng=1.6.17
- libxml2=2.9.2
- llvmlite=0.9.0
- lmfit
- matplotlib=1.5.1
- mkl=11.3.1
- mock=1.3.0
- nose=1.3.7
- numba=0.24.0
- numexpr=2.5
- numpy=1.10.4
- openssl=1.0.2g
- pandas=0.18.0
- pbr=1.3.0
- phconvert
- pip=8.1.1
- pyparsing=2.0.3
- pyqt=4.11.4
- pytables=3.2.2
- python=3.5.1
- python-dateutil=2.5.1
- pytz=2016.2
- qt=4.8.7
- readline=6.2
- scipy=0.17.0
- seaborn=0.7.0
- setuptools=20.3
- sip=4.16.9
- six=1.10.0
- sqlite=3.9.2
- tk=8.5.18
- wheel=0.29.0
- xz=5.0.5
- zlib=1.2.8
- pip:
  - tables==3.2.2
