name: jupyter
channels:
- conda-forge
- defaults
dependencies:
- backports.shutil_get_terminal_size=1.0.0=py_2
- backports_abc=0.5=py27_0
- blas=1.1=openblas
- bleach=2.0.0=py27_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py27_0
- configparser=3.5.0=py27_0
- cycler=0.10.0=py27_0
- decorator=4.1.2=py27_0
- entrypoints=0.2.3=py27_1
- enum34=1.1.6=py27_1
- freetype=2.7=1
- functools32=3.2.3.2=py27_1
- html5lib=0.999999999=py27_0
- icu=58.1=1
- ipykernel=4.6.1=py27_0
- ipython=5.5.0=py27_0
- ipython_genutils=0.2.0=py27_0
- ipywidgets=7.0.1=py_2
- jinja2=2.9.6=py27_0
- jpeg=9b=0
- jsonschema=2.6.0=py27_0
- jupyter=1.0.0=py27_0
- jupyter_client=5.1.0=py27_0
- jupyter_console=5.1.0=py27_0
- jupyter_core=4.3.0=py27_0
- libpng=1.6.28=0
- libsodium=1.0.10=0
- markupsafe=1.0=py27_0
- matplotlib=2.0.2=py27_2
- mistune=0.7.4=py27_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py27_0
- ncurses=5.9=10
- notebook=5.1.0=py27_0
- numpy=1.13.1=py27_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py27_0
- path.py=10.3.1=py27_0
- pathlib2=2.3.0=py27_0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_0
- prompt_toolkit=1.0.15=py27_0
- ptyprocess=0.5.2=py27_0
- pygments=2.2.0=py27_0
- pyparsing=2.2.0=py27_0
- pyqt=5.6.0=py27_4
- python=2.7.13=1
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- pyzmq=16.0.2=py27_2
- qtconsole=4.3.1=py27_0
- readline=6.2=0
- scandir=1.5=py27_1
- scipy=0.19.1=py27_blas_openblas_202
- setuptools=36.3.0=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_1
- six=1.10.0=py27_1
- sqlite=3.13.0=1
- ssl_match_hostname=3.5.0.1=py27_1
- subprocess32=3.2.7=py27_0
- terminado=0.6=py27_0
- testpath=0.3.1=py27_0
- tk=8.5.19=2
- tornado=4.5.2=py27_0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- webencodings=0.5=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=3.0.3=py_1
- zeromq=4.2.1=1
- zlib=1.2.11=0
- backports=1.0=py27_0
- get_terminal_size=1.0.0=py27_0
- mkl=2017.0.3=0
- pip:
  - anyjson==0.3.3
  - ase==3.11.0
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - billiard==3.3.0.19
  - celery==3.1.17
  - django==1.7.4
  - django-celery==3.1.16
  - django-extensions==1.5.0
  - django-tastypie==0.12.1
  - ecdsa==0.13
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - meld3==1.0.0
  - paramiko==1.15.2
  - prompt-toolkit==1.0.15
  - psycopg2==2.6
  - pycrypto==2.6.1
  - python-mimeparse==0.1.4
  - supervisor==3.1.3

